apiVersion: v1
kind: Service
metadata:
  name: db-travellist
  namespace: travellist
spec:
  selector:
    app: travellist
  ports:
    - port: 3306
      targetPort: 3306
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-travellist
  namespace: travellist
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /var/lib/mysql
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-travellist-volume-claim
  namespace: travellist
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-deployment
  namespace: travellist
  labels:
    app: travellist
spec:
  # serviceName: db
  replicas: 5
  selector:
    matchLabels:
      app: travellist
  template:
    metadata:
      labels:
       app: travellist
    spec:
      containers:
      - name:  travellist
        image:  mysql:5.7
        resources:
        ports:
        - containerPort:  3306
          name:  travellist
        env:
          - name: MYSQL_DATABASE
            value: "travellist"
          - name: MYSQL_ROOT_PASSWORD
            value: "password"
          - name: MYSQL_PASSWORD
            value: "password"
          - name: SERVICE_TAGS
            value: "dev"
          - name: SERVICE_NAME
            value: "mysql"
        volumeMounts:
        - name: db-config
          mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: db-config
          configMap:
            name: db-config
        - name: db-travellist-volume-claim
          persistentVolumeClaim:
            claimName: db-travellist-volume-claim
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-db-travellist
  namespace: travellist
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: db-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
